sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '8'
cache:
  yarn: true
branches:
  except:
    - stable
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm i -g yarn
install:
  - yarn add @ckeditor/ckeditor5-dev-tests
  - ckeditor5-dev-tests-install-dependencies
script:
  - ckeditor5-dev-tests-travis
after_success:
  - ckeditor5-dev-tests-save-revision
env:
  global:
    - secure: wLchC7I9H4p743AlJBMFfoCKmR1xQDJIbInZtts6y50wyQjF9GgVFVsuRHIOGis0WD6EXEhqxe+jxSOZfaCcNGQ7TyfRoMdYOs+imLr63Y/2ZDuo/Ceeiibo+aAm6kovs8XtoTV37To1tIN4Fwm6ObRqBBkA3e34fj8Tz9ox6dQWRDDRUyCs3JM7jPieNtc7Uh5m8zLDfmOhemX57NBzEonvmiHKAAnC1mUEiSyqGS5sD4NvxWYfbbTHqtG3ZEz4c1GVVINkfu1A6eQ7hdolwXLVtkRut4hMDK3F7xK6RX2MrWqADk4ka43UqOTN4G8ZZXWmzulfhjQydEQ4UnETVPsCRM8CyyNwhwSi8SHoilOZSTakp4iw5ehH8voGfUq1H0pEuaXLG2fq2LPJepcXXYUw976ZGAj5BwW+D8SFyum/RUb0suk9bUBlD6vrOk6Aj9BeBsa0aSNdm0QyfbFu3GtXofvki6NH8IWOweiFTNr5xKiKp2jWMpAMaWCrICwr+kNKZJ2hvOMsEhwwFnSgfg2Uhop/cL2J9VO8VhPcRjBwPSmqqKaMcnPvqbXrRHhQODu41CXHH6tKFYN3rQauxTv3KzwKwBY19urAg2V0/HLhpxxGsTVeowQ6Pj9gqKuGaRnAvSbjYrr6KaQv3ziE4iHUhR5Y8F3BmY3g6nmnRCY=
    - secure: y7AO+1zAUbd2gxIIKPon48VAEvNMT0tmpp6qAVJ7PWKReKkk7+emCnwEAf29g44M+StpRt+4T7CdFeP3jp/hXuxogO1J84RRBLT08GFB+5M3p6cETfXvruX6ZP3FiznYiFsxL6lAqnCqf4PAD3pxfV44jpGrUXoyIldfsdmjuErG5YrMBpZNlbrPFoenaB1sr4IirF3orE6uPlFdwdNbugXeqagmKukZftSU4TSOGoC62JHXFdkPFXOyJXF0t3GHkMWCGiHxSBaLfj4P+r+Om7ZmB8WJUwhaQnuAOMur+/BykfitRogytKFEITaIVudYOsohZ3MjymCV+6e3tnikr1uCdD/eFKjgQ+GKzSBN4UBFEOf2896mdoe448nGuS1R+QOn8qeW4rQn/p3Z+aDxjNof8scYaYiFKS/l3MdYh95vndppnSBdhFcLaXqXe2u+l5hSnch5szhQx716uom68h5YNeRmpaRecJz9wkC2QXPkulNIgKn405PpnamQg9Z8IBFNXzOl9xuUmHJYWvwf01dEq/FapI5TluGnRhNtTF9oLTEv3SejC12bQjJh2l/z2dTrLPE37W5R/DsA2iMuh5YZDi/6dQAfBfjE++spiEwr5UDbdZa+YL11oFOJBp18teKmGdIs9K/BQt0DjxhfIsxINf4JIE8zGCq+ZsruRXc=
